# #########################################################################
# Creates a new release using `workflow_dispatch` event trigger with `type`
# as input to describe the type of release to create
name: 'Release-it: Create a new release on demand'

on:
  workflow_dispatch:
    inputs:
      type:
        description: 'Type. Can be `patch` `minor` or `major`'
        required: true
        default: 'patch'
jobs:
  release-it:
    runs-on: [ubuntu-latest]
    strategy:
      matrix:
        node-version: [18.10.0]
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Checkout master
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3.4.1
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build packages
        run: bash package.sh 1

      - name: Upload windows x64 package
        uses: actions/upload-artifact@v3
        with:
          name: win-x64
          path: pkg/*-win-x64.tgz

      - name: Upload linux amd64 package
        uses: actions/upload-artifact@v3
        with:
          name: linux-amd64
          path: pkg/*-linux-amd64.tgz

      - name: Upload linux arm64 package
        uses: actions/upload-artifact@v3
        with:
          name: linux-arm64
          path: pkg/*-linux-arm64.tgz
